########################################################
# IAM · Menu（菜单）
########################################################

########################################################
# Query（查询）
########################################################

###
# 菜单
GET {{host}}/api/v1/iam/menus/tree

########################################################
# Command（变更）
########################################################

###
# 新增菜单
POST {{host}}/api/v1/iam/menus
Content-Type: application/json

{
  "parentId": 0,
  "type": "",
  "title": "",
  "name": "",
  "path": "",
  "component": "",
  "icon": "",
  "sortOrder": 0
}

###
# 修改菜单
POST {{host}}/api/v1/iam/menus/3
Content-Type: application/json

{
  "type": "",
  "title": "",
  "name": "",
  "path": "",
  "component": "",
  "icon": "",
  "sortOrder": 0
}

###
# 删除菜单（单个）
DELETE {{host}}/api/v1/iam/menus/5

########################################################
# Relationship（关系）
# 第一种：Relationship Replace（整体维护）
########################################################
